### ISSUE TITLE
Image names are transacted as images even if they point at manifest-lists

### ISSUE THREAD

**Issue by cdupuis** [atomist-skills/deploy-integration#17]
Example "kong@sha256:a1716e361096a5dbf8b6a09b2292001d39b9818a02f224e03f96052b1c81d5a5"  from our k8s cluster.

```
skopeo inspect 'docker://kong@sha256:a1716e361096a5dbf8b6a09b2292001d39b9818a02f224e03f96052b1c81d5a5' --raw | jq .
{
  "manifests": [
    {
      "digest": "sha256:21ca915f309f364e5ff5e1f9d2edaeff9eb19c5768b3ffbab2cc3311300bbe4c",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      },
      "size": 1781
    },
    {
      "digest": "sha256:81dfcde0556d865b476b8196a95cdb57aa5798c06e1f9276b91565196105f648",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "arm64",
        "os": "linux",
        "variant": "v8"
      },
      "size": 1781
    }
  ],
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "schemaVersion": 2
}

```

**Comment by slimslenderslacks** [comment]
We could go back to transacting a `:deployment.environment/image-url` as a `:db.type/string`.  The docker-capability, and other docker registry integrations could subscribe to those and and then transact the `:db.type/ref` on the environment with the logic that's already present in those integrations.  We wouldn't be able to transact image refs for repos that we can't query, but we'd know about them because there would be entities with `image-url` but with no `image` ref.

Another issue the caller has no way of telling us which architecture was actually used.  Should we be allowing callers to send the URL for the manifest plus the architecture that they're actually using.  Is that useful?

**Comment by kipz** [comment]
Yeah, I think it is useful. In fact, that would allow us to figure out which images is used.

Is there really no way to get the image that was used by k8s?

**Comment by cdupuis** [comment]
> Is there really no way to get the image that was used by k8s?

Not that I know of. k8s kubelet sends the container creation request to containerd and lets it figure out what image to run. In the k8s APIs there is only the digest I'm sending in the Webhooks.
